package qjtx.dao;

import org.apache.ibatis.annotations.Param;

import qjtx.pojo.Operationuser;
import qjtx.pojo.SalesDataStore;

public interface OperationuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_user
     *
     * @mbg.generated Thu Nov 10 19:49:39 CST 2016
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_user
     *
     * @mbg.generated Thu Nov 10 19:49:39 CST 2016
     */
    int insert(Operationuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_user
     *
     * @mbg.generated Thu Nov 10 19:49:39 CST 2016
     */
    int insertSelective(Operationuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_user
     *
     * @mbg.generated Thu Nov 10 19:49:39 CST 2016
     */
    Operationuser selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_user
     *
     * @mbg.generated Thu Nov 10 19:49:39 CST 2016
     */
    int updateByPrimaryKeySelective(Operationuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_user
     *
     * @mbg.generated Thu Nov 10 19:49:39 CST 2016
     */
    int updateByPrimaryKey(Operationuser record);
    
	Operationuser checkpassword(
			@Param("userstring")String userstring);
}