package qjtx.dao;

import qjtx.pojo.Qjorders;

public interface QjordersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qj_orders
     *
     * @mbg.generated Wed May 03 17:29:14 CST 2017
     */
    int deleteByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qj_orders
     *
     * @mbg.generated Wed May 03 17:29:14 CST 2017
     */
    int insert(Qjorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qj_orders
     *
     * @mbg.generated Wed May 03 17:29:14 CST 2017
     */
    int insertSelective(Qjorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qj_orders
     *
     * @mbg.generated Wed May 03 17:29:14 CST 2017
     */
    Qjorders selectByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qj_orders
     *
     * @mbg.generated Wed May 03 17:29:14 CST 2017
     */
    int updateByPrimaryKeySelective(Qjorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qj_orders
     *
     * @mbg.generated Wed May 03 17:29:14 CST 2017
     */
    int updateByPrimaryKey(Qjorders record);
}