package qjtx.pojo;

public class Qjitemtypes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_itemtypes.itemid
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    private String itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_itemtypes.resultstring
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    private String resultstring;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_itemtypes.tctype
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    private String tctype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_itemtypes.tcprice
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    private String tcprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_itemtypes.tcperiod
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    private String tcperiod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_itemtypes.itemid
     *
     * @return the value of qj_itemtypes.itemid
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    public String getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_itemtypes.itemid
     *
     * @param itemid the value for qj_itemtypes.itemid
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    public void setItemid(String itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_itemtypes.resultstring
     *
     * @return the value of qj_itemtypes.resultstring
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    public String getResultstring() {
        return resultstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_itemtypes.resultstring
     *
     * @param resultstring the value for qj_itemtypes.resultstring
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    public void setResultstring(String resultstring) {
        this.resultstring = resultstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_itemtypes.tctype
     *
     * @return the value of qj_itemtypes.tctype
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    public String getTctype() {
        return tctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_itemtypes.tctype
     *
     * @param tctype the value for qj_itemtypes.tctype
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    public void setTctype(String tctype) {
        this.tctype = tctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_itemtypes.tcprice
     *
     * @return the value of qj_itemtypes.tcprice
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    public String getTcprice() {
        return tcprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_itemtypes.tcprice
     *
     * @param tcprice the value for qj_itemtypes.tcprice
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    public void setTcprice(String tcprice) {
        this.tcprice = tcprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_itemtypes.tcperiod
     *
     * @return the value of qj_itemtypes.tcperiod
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    public String getTcperiod() {
        return tcperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_itemtypes.tcperiod
     *
     * @param tcperiod the value for qj_itemtypes.tcperiod
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    public void setTcperiod(String tcperiod) {
        this.tcperiod = tcperiod;
    }
}