package qjtx.pojo;

public class Qjoperaters {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qj_operaters.operaterid
	 * @mbg.generated  Sun May 21 23:18:35 CST 2017
	 */
	private String operaterid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qj_operaters.opassword
	 * @mbg.generated  Sun May 21 23:18:35 CST 2017
	 */
	private String opassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qj_operaters.operatername
	 * @mbg.generated  Sun May 21 23:18:35 CST 2017
	 */
	private String operatername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qj_operaters.operatergroup
	 * @mbg.generated  Sun May 21 23:18:35 CST 2017
	 */
	private String operatergroup;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qj_operaters.omobile
	 * @mbg.generated  Sun May 21 23:18:35 CST 2017
	 */
	private String omobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qj_operaters.omail
	 * @mbg.generated  Sun May 21 23:18:35 CST 2017
	 */
	private String omail;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qj_operaters.operaterid
	 * @return  the value of qj_operaters.operaterid
	 * @mbg.generated  Sun May 21 23:18:35 CST 2017
	 */
	public String getOperaterid() {
		return operaterid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qj_operaters.operaterid
	 * @param operaterid  the value for qj_operaters.operaterid
	 * @mbg.generated  Sun May 21 23:18:35 CST 2017
	 */
	public void setOperaterid(String operaterid) {
		this.operaterid = operaterid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qj_operaters.opassword
	 * @return  the value of qj_operaters.opassword
	 * @mbg.generated  Sun May 21 23:18:35 CST 2017
	 */
	public String getOpassword() {
		return opassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qj_operaters.opassword
	 * @param opassword  the value for qj_operaters.opassword
	 * @mbg.generated  Sun May 21 23:18:35 CST 2017
	 */
	public void setOpassword(String opassword) {
		this.opassword = opassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qj_operaters.operatername
	 * @return  the value of qj_operaters.operatername
	 * @mbg.generated  Sun May 21 23:18:35 CST 2017
	 */
	public String getOperatername() {
		return operatername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qj_operaters.operatername
	 * @param operatername  the value for qj_operaters.operatername
	 * @mbg.generated  Sun May 21 23:18:35 CST 2017
	 */
	public void setOperatername(String operatername) {
		this.operatername = operatername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qj_operaters.operatergroup
	 * @return  the value of qj_operaters.operatergroup
	 * @mbg.generated  Sun May 21 23:18:35 CST 2017
	 */
	public String getOperatergroup() {
		return operatergroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qj_operaters.operatergroup
	 * @param operatergroup  the value for qj_operaters.operatergroup
	 * @mbg.generated  Sun May 21 23:18:35 CST 2017
	 */
	public void setOperatergroup(String operatergroup) {
		this.operatergroup = operatergroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qj_operaters.omobile
	 * @return  the value of qj_operaters.omobile
	 * @mbg.generated  Sun May 21 23:18:35 CST 2017
	 */
	public String getOmobile() {
		return omobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qj_operaters.omobile
	 * @param omobile  the value for qj_operaters.omobile
	 * @mbg.generated  Sun May 21 23:18:35 CST 2017
	 */
	public void setOmobile(String omobile) {
		this.omobile = omobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qj_operaters.omail
	 * @return  the value of qj_operaters.omail
	 * @mbg.generated  Sun May 21 23:18:35 CST 2017
	 */
	public String getOmail() {
		return omail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qj_operaters.omail
	 * @param omail  the value for qj_operaters.omail
	 * @mbg.generated  Sun May 21 23:18:35 CST 2017
	 */
	public void setOmail(String omail) {
		this.omail = omail;
	}
}