package qjtx.pojo;

import java.util.Date;

public class VReportSalesDataForOp {
	
	private int id;
	
    public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

    private String imgfile1;
    public String getImgfile1() {
		return imgfile1;
	}

	public void setImgfile1(String imgfile1) {
		this.imgfile1 = imgfile1;
	}

	public String getImgfile2() {
		return imgfile2;
	}

	public void setImgfile2(String imgfile2) {
		this.imgfile2 = imgfile2;
	}

	public String getImgfile3() {
		return imgfile3;
	}

	public void setImgfile3(String imgfile3) {
		this.imgfile3 = imgfile3;
	}

	public String getImgfile4() {
		return imgfile4;
	}

	public void setImgfile4(String imgfile4) {
		this.imgfile4 = imgfile4;
	}

	private String imgfile2;
    private String imgfile3;
    private String imgfile4;
    
	private Integer cid;


    private String saleid;


    private String storename;
    
    private String contact;
    
    private String phone;

    public String getContact() {
		return contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	private String productid;
    
    public String getProductid() {
		return productid;
	}

	public void setProductid(String productid) {
		this.productid = productid;
	}

	private String floor;
    
    public String getFloor() {
		return floor;
	}

	public void setFloor(String floor) {
		this.floor = floor;
	}

	private Date saleday;


    private Double saletotal;


    private Integer qty;

    
    private String imgfile;


    private Integer reviewed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_report_salesdata.cid
     *
     * @return the value of v_report_salesdata.cid
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_report_salesdata.cid
     *
     * @param cid the value for v_report_salesdata.cid
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_report_salesdata.saleid
     *
     * @return the value of v_report_salesdata.saleid
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public String getSaleid() {
        return saleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_report_salesdata.saleid
     *
     * @param saleid the value for v_report_salesdata.saleid
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public void setSaleid(String saleid) {
        this.saleid = saleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_report_salesdata.storename
     *
     * @return the value of v_report_salesdata.storename
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public String getStorename() {
        return storename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_report_salesdata.storename
     *
     * @param storename the value for v_report_salesdata.storename
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public void setStorename(String storename) {
        this.storename = storename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_report_salesdata.saleday
     *
     * @return the value of v_report_salesdata.saleday
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public Date getSaleday() {
        return saleday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_report_salesdata.saleday
     *
     * @param saleday the value for v_report_salesdata.saleday
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public void setSaleday(Date saleday) {
        this.saleday = saleday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_report_salesdata.saletotal
     *
     * @return the value of v_report_salesdata.saletotal
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public Double getSaletotal() {
        return saletotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_report_salesdata.saletotal
     *
     * @param saletotal the value for v_report_salesdata.saletotal
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public void setSaletotal(Double saletotal) {
        this.saletotal = saletotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_report_salesdata.qty
     *
     * @return the value of v_report_salesdata.qty
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_report_salesdata.qty
     *
     * @param qty the value for v_report_salesdata.qty
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_report_salesdata.imgfile
     *
     * @return the value of v_report_salesdata.imgfile
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public String getImgfile() {
        return imgfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_report_salesdata.imgfile
     *
     * @param imgfile the value for v_report_salesdata.imgfile
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public void setImgfile(String imgfile) {
        this.imgfile = imgfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_report_salesdata.reviewed
     *
     * @return the value of v_report_salesdata.reviewed
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public Integer getReviewed() {
        return reviewed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_report_salesdata.reviewed
     *
     * @param reviewed the value for v_report_salesdata.reviewed
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public void setReviewed(Integer reviewed) {
        this.reviewed = reviewed;
    }
}