package qjtx.dao;

import qjtx.pojo.Qjitemtypes;

public interface QjitemtypesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qj_itemtypes
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    int deleteByPrimaryKey(String itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qj_itemtypes
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    int insert(Qjitemtypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qj_itemtypes
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    int insertSelective(Qjitemtypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qj_itemtypes
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    Qjitemtypes selectByPrimaryKey(String itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qj_itemtypes
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    int updateByPrimaryKeySelective(Qjitemtypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qj_itemtypes
     *
     * @mbg.generated Thu Jun 22 19:55:42 CST 2017
     */
    int updateByPrimaryKey(Qjitemtypes record);
}