package qjtx.dao;

import qjtx.pojo.Qjoperaters;

public interface QjoperatersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qj_operaters
	 * @mbg.generated  Mon May 08 22:53:19 CST 2017
	 */
	int deleteByPrimaryKey(String operaterid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qj_operaters
	 * @mbg.generated  Mon May 08 22:53:19 CST 2017
	 */
	int insert(Qjoperaters record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qj_operaters
	 * @mbg.generated  Mon May 08 22:53:19 CST 2017
	 */
	int insertSelective(Qjoperaters record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qj_operaters
	 * @mbg.generated  Mon May 08 22:53:19 CST 2017
	 */
	Qjoperaters selectByPrimaryKey(String operaterid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qj_operaters
	 * @mbg.generated  Mon May 08 22:53:19 CST 2017
	 */
	int updateByPrimaryKeySelective(Qjoperaters record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qj_operaters
	 * @mbg.generated  Mon May 08 22:53:19 CST 2017
	 */
	int updateByPrimaryKey(Qjoperaters record);
}