package qjtx.dao;

import org.apache.ibatis.annotations.Param;

import qjtx.pojo.SalesDataStore;

public interface SalesDataStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesdata_store
     *
     * @mbg.generated Thu Nov 03 13:17:49 CST 2016
     */
    int insert(SalesDataStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesdata_store
     *
     * @mbg.generated Thu Nov 03 13:17:49 CST 2016
     */
    int insertSelective(SalesDataStore record);
    
    
	SalesDataStore selectByLinkString(
			@Param("linkstring")String linkstring);
}