package qjtx.pojo;

import java.util.Date;

public class Qjorders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.orderid
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.ordertime
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private Date ordertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.mobile
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.customname
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private String customname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.broaddistrict
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private String broaddistrict;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.broadaddress
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private String broadaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.customid
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private String customid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.customimages
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private String customimages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.content
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.status
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.donetime
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private Date donetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.info01
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private String info01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.info02
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private String info02;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.info03
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private String info03;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.info04
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private String info04;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.doneuserid
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private Integer doneuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.tokenstring
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private String tokenstring;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.orderid
     *
     * @return the value of qj_orders.orderid
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.orderid
     *
     * @param orderid the value for qj_orders.orderid
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.ordertime
     *
     * @return the value of qj_orders.ordertime
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.ordertime
     *
     * @param ordertime the value for qj_orders.ordertime
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.mobile
     *
     * @return the value of qj_orders.mobile
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.mobile
     *
     * @param mobile the value for qj_orders.mobile
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.customname
     *
     * @return the value of qj_orders.customname
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public String getCustomname() {
        return customname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.customname
     *
     * @param customname the value for qj_orders.customname
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setCustomname(String customname) {
        this.customname = customname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.broaddistrict
     *
     * @return the value of qj_orders.broaddistrict
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public String getBroaddistrict() {
        return broaddistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.broaddistrict
     *
     * @param broaddistrict the value for qj_orders.broaddistrict
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setBroaddistrict(String broaddistrict) {
        this.broaddistrict = broaddistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.broadaddress
     *
     * @return the value of qj_orders.broadaddress
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public String getBroadaddress() {
        return broadaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.broadaddress
     *
     * @param broadaddress the value for qj_orders.broadaddress
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setBroadaddress(String broadaddress) {
        this.broadaddress = broadaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.customid
     *
     * @return the value of qj_orders.customid
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public String getCustomid() {
        return customid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.customid
     *
     * @param customid the value for qj_orders.customid
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setCustomid(String customid) {
        this.customid = customid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.customimages
     *
     * @return the value of qj_orders.customimages
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public String getCustomimages() {
        return customimages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.customimages
     *
     * @param customimages the value for qj_orders.customimages
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setCustomimages(String customimages) {
        this.customimages = customimages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.content
     *
     * @return the value of qj_orders.content
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.content
     *
     * @param content the value for qj_orders.content
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.status
     *
     * @return the value of qj_orders.status
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.status
     *
     * @param status the value for qj_orders.status
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.donetime
     *
     * @return the value of qj_orders.donetime
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public Date getDonetime() {
        return donetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.donetime
     *
     * @param donetime the value for qj_orders.donetime
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setDonetime(Date donetime) {
        this.donetime = donetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.info01
     *
     * @return the value of qj_orders.info01
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public String getInfo01() {
        return info01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.info01
     *
     * @param info01 the value for qj_orders.info01
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setInfo01(String info01) {
        this.info01 = info01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.info02
     *
     * @return the value of qj_orders.info02
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public String getInfo02() {
        return info02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.info02
     *
     * @param info02 the value for qj_orders.info02
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setInfo02(String info02) {
        this.info02 = info02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.info03
     *
     * @return the value of qj_orders.info03
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public String getInfo03() {
        return info03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.info03
     *
     * @param info03 the value for qj_orders.info03
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setInfo03(String info03) {
        this.info03 = info03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.info04
     *
     * @return the value of qj_orders.info04
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public String getInfo04() {
        return info04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.info04
     *
     * @param info04 the value for qj_orders.info04
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setInfo04(String info04) {
        this.info04 = info04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.doneuserid
     *
     * @return the value of qj_orders.doneuserid
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public Integer getDoneuserid() {
        return doneuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.doneuserid
     *
     * @param doneuserid the value for qj_orders.doneuserid
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setDoneuserid(Integer doneuserid) {
        this.doneuserid = doneuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.tokenstring
     *
     * @return the value of qj_orders.tokenstring
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public String getTokenstring() {
        return tokenstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.tokenstring
     *
     * @param tokenstring the value for qj_orders.tokenstring
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setTokenstring(String tokenstring) {
        this.tokenstring = tokenstring;
    }
}