package qjtx.pojo;

import java.util.Date;

public class Qjorders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.orderid
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.orderdate
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private Date orderdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.ordertime
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private Date ordertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.orderprice
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private Double orderprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.operatetime
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private Date operatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.operaterid
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private String operaterid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.operatestatus
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private Integer operatestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.monthly_fee
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private Double monthly_fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.broadband_rat
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private Integer broadband_rat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.effective_date
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private Date effective_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.contract_period
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private String contract_period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.package_details
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private String package_details;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.package_name
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private String package_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.operatorcompany
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private String operatorcompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.broadband_account
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private String broadband_account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.mobile
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.id_number
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private String id_number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.cname
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.service_type
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private String service_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.installation_address
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private String installation_address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.package_price
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private Double package_price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.attach_info
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private String attach_info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.mix_user_id
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private String mix_user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.item_id
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private String item_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_orders.id_images
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    private String id_images;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.orderid
     *
     * @return the value of qj_orders.orderid
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.orderid
     *
     * @param orderid the value for qj_orders.orderid
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.orderdate
     *
     * @return the value of qj_orders.orderdate
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public Date getOrderdate() {
        return orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.orderdate
     *
     * @param orderdate the value for qj_orders.orderdate
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.ordertime
     *
     * @return the value of qj_orders.ordertime
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.ordertime
     *
     * @param ordertime the value for qj_orders.ordertime
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.orderprice
     *
     * @return the value of qj_orders.orderprice
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public Double getOrderprice() {
        return orderprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.orderprice
     *
     * @param orderprice the value for qj_orders.orderprice
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setOrderprice(Double orderprice) {
        this.orderprice = orderprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.operatetime
     *
     * @return the value of qj_orders.operatetime
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public Date getOperatetime() {
        return operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.operatetime
     *
     * @param operatetime the value for qj_orders.operatetime
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setOperatetime(Date operatetime) {
        this.operatetime = operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.operaterid
     *
     * @return the value of qj_orders.operaterid
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public String getOperaterid() {
        return operaterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.operaterid
     *
     * @param operaterid the value for qj_orders.operaterid
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setOperaterid(String operaterid) {
        this.operaterid = operaterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.operatestatus
     *
     * @return the value of qj_orders.operatestatus
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public Integer getOperatestatus() {
        return operatestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.operatestatus
     *
     * @param operatestatus the value for qj_orders.operatestatus
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setOperatestatus(Integer operatestatus) {
        this.operatestatus = operatestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.monthly_fee
     *
     * @return the value of qj_orders.monthly_fee
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public Double getMonthly_fee() {
        return monthly_fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.monthly_fee
     *
     * @param monthly_fee the value for qj_orders.monthly_fee
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setMonthly_fee(Double monthly_fee) {
        this.monthly_fee = monthly_fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.broadband_rat
     *
     * @return the value of qj_orders.broadband_rat
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public Integer getBroadband_rat() {
        return broadband_rat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.broadband_rat
     *
     * @param broadband_rat the value for qj_orders.broadband_rat
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setBroadband_rat(Integer broadband_rat) {
        this.broadband_rat = broadband_rat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.effective_date
     *
     * @return the value of qj_orders.effective_date
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public Date getEffective_date() {
        return effective_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.effective_date
     *
     * @param effective_date the value for qj_orders.effective_date
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setEffective_date(Date effective_date) {
        this.effective_date = effective_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.contract_period
     *
     * @return the value of qj_orders.contract_period
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public String getContract_period() {
        return contract_period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.contract_period
     *
     * @param contract_period the value for qj_orders.contract_period
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setContract_period(String contract_period) {
        this.contract_period = contract_period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.package_details
     *
     * @return the value of qj_orders.package_details
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public String getPackage_details() {
        return package_details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.package_details
     *
     * @param package_details the value for qj_orders.package_details
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setPackage_details(String package_details) {
        this.package_details = package_details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.package_name
     *
     * @return the value of qj_orders.package_name
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public String getPackage_name() {
        return package_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.package_name
     *
     * @param package_name the value for qj_orders.package_name
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setPackage_name(String package_name) {
        this.package_name = package_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.operatorcompany
     *
     * @return the value of qj_orders.operatorcompany
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public String getOperatorcompany() {
        return operatorcompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.operatorcompany
     *
     * @param operatorcompany the value for qj_orders.operatorcompany
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setOperatorcompany(String operatorcompany) {
        this.operatorcompany = operatorcompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.broadband_account
     *
     * @return the value of qj_orders.broadband_account
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public String getBroadband_account() {
        return broadband_account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.broadband_account
     *
     * @param broadband_account the value for qj_orders.broadband_account
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setBroadband_account(String broadband_account) {
        this.broadband_account = broadband_account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.mobile
     *
     * @return the value of qj_orders.mobile
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.mobile
     *
     * @param mobile the value for qj_orders.mobile
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.id_number
     *
     * @return the value of qj_orders.id_number
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public String getId_number() {
        return id_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.id_number
     *
     * @param id_number the value for qj_orders.id_number
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setId_number(String id_number) {
        this.id_number = id_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.cname
     *
     * @return the value of qj_orders.cname
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.cname
     *
     * @param cname the value for qj_orders.cname
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.service_type
     *
     * @return the value of qj_orders.service_type
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public String getService_type() {
        return service_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.service_type
     *
     * @param service_type the value for qj_orders.service_type
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setService_type(String service_type) {
        this.service_type = service_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.installation_address
     *
     * @return the value of qj_orders.installation_address
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public String getInstallation_address() {
        return installation_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.installation_address
     *
     * @param installation_address the value for qj_orders.installation_address
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setInstallation_address(String installation_address) {
        this.installation_address = installation_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.package_price
     *
     * @return the value of qj_orders.package_price
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public Double getPackage_price() {
        return package_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.package_price
     *
     * @param package_price the value for qj_orders.package_price
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setPackage_price(Double package_price) {
        this.package_price = package_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.attach_info
     *
     * @return the value of qj_orders.attach_info
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public String getAttach_info() {
        return attach_info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.attach_info
     *
     * @param attach_info the value for qj_orders.attach_info
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setAttach_info(String attach_info) {
        this.attach_info = attach_info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.mix_user_id
     *
     * @return the value of qj_orders.mix_user_id
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public String getMix_user_id() {
        return mix_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.mix_user_id
     *
     * @param mix_user_id the value for qj_orders.mix_user_id
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setMix_user_id(String mix_user_id) {
        this.mix_user_id = mix_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.item_id
     *
     * @return the value of qj_orders.item_id
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public String getItem_id() {
        return item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.item_id
     *
     * @param item_id the value for qj_orders.item_id
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setItem_id(String item_id) {
        this.item_id = item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_orders.id_images
     *
     * @return the value of qj_orders.id_images
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public String getId_images() {
        return id_images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_orders.id_images
     *
     * @param id_images the value for qj_orders.id_images
     *
     * @mbg.generated Tue May 02 19:11:27 CST 2017
     */
    public void setId_images(String id_images) {
        this.id_images = id_images;
    }
}