package qjtx.pojo;

public class Qjuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_user.userid
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_user.userstring
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private String userstring;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_user.username
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_user.password
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_user.group
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private String group;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_user.mail
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_user.phone
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qj_user.company
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    private String company;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_user.userid
     *
     * @return the value of qj_user.userid
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_user.userid
     *
     * @param userid the value for qj_user.userid
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_user.userstring
     *
     * @return the value of qj_user.userstring
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public String getUserstring() {
        return userstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_user.userstring
     *
     * @param userstring the value for qj_user.userstring
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setUserstring(String userstring) {
        this.userstring = userstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_user.username
     *
     * @return the value of qj_user.username
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_user.username
     *
     * @param username the value for qj_user.username
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_user.password
     *
     * @return the value of qj_user.password
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_user.password
     *
     * @param password the value for qj_user.password
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_user.group
     *
     * @return the value of qj_user.group
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public String getGroup() {
        return group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_user.group
     *
     * @param group the value for qj_user.group
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setGroup(String group) {
        this.group = group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_user.mail
     *
     * @return the value of qj_user.mail
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_user.mail
     *
     * @param mail the value for qj_user.mail
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_user.phone
     *
     * @return the value of qj_user.phone
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_user.phone
     *
     * @param phone the value for qj_user.phone
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qj_user.company
     *
     * @return the value of qj_user.company
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qj_user.company
     *
     * @param company the value for qj_user.company
     *
     * @mbg.generated Thu Apr 27 11:20:05 CST 2017
     */
    public void setCompany(String company) {
        this.company = company;
    }
}