package qjtx.pojo;

public class SalesDataStore {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column salesdata_store.saleid
	 * 
	 * @mbg.generated Thu Nov 03 13:17:49 CST 2016
	 */
	private String saleid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column salesdata_store.linkstring
	 * 
	 * @mbg.generated Thu Nov 03 13:17:49 CST 2016
	 */
	private String linkstring;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column salesdata_store.storename
	 * 
	 * @mbg.generated Thu Nov 03 13:17:49 CST 2016
	 */
	private String storename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column salesdata_store.productid
	 * 
	 * @mbg.generated Thu Nov 03 13:17:49 CST 2016
	 */
	private String productid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column salesdata_store.floor
	 * 
	 * @mbg.generated Thu Nov 03 13:17:49 CST 2016
	 */
	private String floor;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column salesdata_store.contact
	 *
	 * @mbg.generated Thu Nov 10 11:26:04 CST 2016
	 */
	private String contact;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column salesdata_store.phone
	 *
	 * @mbg.generated Thu Nov 10 11:26:04 CST 2016
	 */
	private String phone;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column salesdata_store.saleid
	 * 
	 * @return the value of salesdata_store.saleid
	 * @mbg.generated Thu Nov 03 13:17:49 CST 2016
	 */
	public String getSaleid() {
		return saleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column salesdata_store.saleid
	 * 
	 * @param saleid
	 *            the value for salesdata_store.saleid
	 * @mbg.generated Thu Nov 03 13:17:49 CST 2016
	 */
	public void setSaleid(String saleid) {
		this.saleid = saleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column salesdata_store.linkstring
	 * 
	 * @return the value of salesdata_store.linkstring
	 * @mbg.generated Thu Nov 03 13:17:49 CST 2016
	 */
	public String getLinkstring() {
		return linkstring;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column salesdata_store.linkstring
	 * 
	 * @param linkstring
	 *            the value for salesdata_store.linkstring
	 * @mbg.generated Thu Nov 03 13:17:49 CST 2016
	 */
	public void setLinkstring(String linkstring) {
		this.linkstring = linkstring;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column salesdata_store.storename
	 * 
	 * @return the value of salesdata_store.storename
	 * @mbg.generated Thu Nov 03 13:17:49 CST 2016
	 */
	public String getStorename() {
		return storename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column salesdata_store.storename
	 * 
	 * @param storename
	 *            the value for salesdata_store.storename
	 * @mbg.generated Thu Nov 03 13:17:49 CST 2016
	 */
	public void setStorename(String storename) {
		this.storename = storename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column salesdata_store.productid
	 * 
	 * @return the value of salesdata_store.productid
	 * @mbg.generated Thu Nov 03 13:17:49 CST 2016
	 */
	public String getProductid() {
		return productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column salesdata_store.productid
	 * 
	 * @param productid
	 *            the value for salesdata_store.productid
	 * @mbg.generated Thu Nov 03 13:17:49 CST 2016
	 */
	public void setProductid(String productid) {
		this.productid = productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column salesdata_store.floor
	 * 
	 * @return the value of salesdata_store.floor
	 * @mbg.generated Thu Nov 03 13:17:49 CST 2016
	 */
	public String getFloor() {
		return floor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column salesdata_store.floor
	 * 
	 * @param floor
	 *            the value for salesdata_store.floor
	 * @mbg.generated Thu Nov 03 13:17:49 CST 2016
	 */
	public void setFloor(String floor) {
		this.floor = floor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column salesdata_store.contact
	 *
	 * @return the value of salesdata_store.contact
	 *
	 * @mbg.generated Thu Nov 10 11:26:04 CST 2016
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column salesdata_store.contact
	 *
	 * @param contact
	 *            the value for salesdata_store.contact
	 *
	 * @mbg.generated Thu Nov 10 11:26:04 CST 2016
	 */
	public void setContact(String contact) {
		this.contact = contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column salesdata_store.phone
	 *
	 * @return the value of salesdata_store.phone
	 *
	 * @mbg.generated Thu Nov 10 11:26:04 CST 2016
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column salesdata_store.phone
	 *
	 * @param phone
	 *            the value for salesdata_store.phone
	 *
	 * @mbg.generated Thu Nov 10 11:26:04 CST 2016
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}
}