package qjtx.pojo;

import java.util.Date;

public class SalesDataDay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesdata_day.cid
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesdata_day.saleid
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    private String saleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesdata_day.saleday
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    private Date saleday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesdata_day.updatetime
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesdata_day.saletotal
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    private Double saletotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesdata_day.qty
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    private Integer qty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesdata_day.imgfile
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    private String imgfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesdata_day.reviewed
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    private Integer reviewed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesdata_day.reviewtime
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    private Date reviewtime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column salesdata_day.reviewopid
    *
    * @mbg.generated Thu Nov 10 11:26:04 CST 2016
    */
   private Integer reviewopid;
   
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesdata_day.cid
     *
     * @return the value of salesdata_day.cid
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesdata_day.cid
     *
     * @param cid the value for salesdata_day.cid
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesdata_day.saleid
     *
     * @return the value of salesdata_day.saleid
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    public String getSaleid() {
        return saleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesdata_day.saleid
     *
     * @param saleid the value for salesdata_day.saleid
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    public void setSaleid(String saleid) {
        this.saleid = saleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesdata_day.saleday
     *
     * @return the value of salesdata_day.saleday
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    public Date getSaleday() {
        return saleday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesdata_day.saleday
     *
     * @param saleday the value for salesdata_day.saleday
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    public void setSaleday(Date saleday) {
        this.saleday = saleday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesdata_day.updatetime
     *
     * @return the value of salesdata_day.updatetime
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesdata_day.updatetime
     *
     * @param updatetime the value for salesdata_day.updatetime
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesdata_day.saletotal
     *
     * @return the value of salesdata_day.saletotal
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    public Double getSaletotal() {
        return saletotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesdata_day.saletotal
     *
     * @param saletotal the value for salesdata_day.saletotal
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    public void setSaletotal(Double saletotal) {
        this.saletotal = saletotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesdata_day.qty
     *
     * @return the value of salesdata_day.qty
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesdata_day.qty
     *
     * @param qty the value for salesdata_day.qty
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesdata_day.imgfile
     *
     * @return the value of salesdata_day.imgfile
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    public String getImgfile() {
        return imgfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesdata_day.imgfile
     *
     * @param imgfile the value for salesdata_day.imgfile
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    public void setImgfile(String imgfile) {
        this.imgfile = imgfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesdata_day.reviewed
     *
     * @return the value of salesdata_day.reviewed
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    public Integer getReviewed() {
        return reviewed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesdata_day.reviewed
     *
     * @param reviewed the value for salesdata_day.reviewed
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    public void setReviewed(Integer reviewed) {
        this.reviewed = reviewed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesdata_day.reviewtime
     *
     * @return the value of salesdata_day.reviewtime
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    public Date getReviewtime() {
        return reviewtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesdata_day.reviewtime
     *
     * @param reviewtime the value for salesdata_day.reviewtime
     *
     * @mbg.generated Mon Nov 07 12:05:58 CST 2016
     */
    public void setReviewtime(Date reviewtime) {
        this.reviewtime = reviewtime;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesdata_day.reviewopid
     *
     * @return the value of salesdata_day.reviewopid
     *
     * @mbg.generated Thu Nov 10 11:26:04 CST 2016
     */
    public Integer getReviewopid() {
        return reviewopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesdata_day.reviewopid
     *
     * @param reviewopid the value for salesdata_day.reviewopid
     *
     * @mbg.generated Thu Nov 10 11:26:04 CST 2016
     */
    public void setReviewopid(Integer reviewopid) {
        this.reviewopid = reviewopid;
    }
}