package qjtx.pojo;

import java.util.Date;

public class VReportSalesData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_report_salesdata.cid
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_report_salesdata.saleid
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    private String saleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_report_salesdata.storename
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    private String storename;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column v_report_salesdata.contact
    *
    * @mbg.generated Thu Nov 10 11:26:04 CST 2016
    */
   private String contact;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column v_report_salesdata.phone
    *
    * @mbg.generated Thu Nov 10 11:26:04 CST 2016
    */
   private String phone;
   
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_report_salesdata.saleday
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    private Date saleday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_report_salesdata.saletotal
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    private Double saletotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_report_salesdata.qty
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    private Integer qty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_report_salesdata.imgfile
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    private String imgfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_report_salesdata.reviewed
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    private Integer reviewed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_report_salesdata.cid
     *
     * @return the value of v_report_salesdata.cid
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_report_salesdata.cid
     *
     * @param cid the value for v_report_salesdata.cid
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_report_salesdata.saleid
     *
     * @return the value of v_report_salesdata.saleid
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public String getSaleid() {
        return saleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_report_salesdata.saleid
     *
     * @param saleid the value for v_report_salesdata.saleid
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public void setSaleid(String saleid) {
        this.saleid = saleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_report_salesdata.storename
     *
     * @return the value of v_report_salesdata.storename
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public String getStorename() {
        return storename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_report_salesdata.storename
     *
     * @param storename the value for v_report_salesdata.storename
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public void setStorename(String storename) {
        this.storename = storename;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_report_salesdata.contact
     *
     * @return the value of v_report_salesdata.contact
     *
     * @mbg.generated Thu Nov 10 11:26:04 CST 2016
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_report_salesdata.contact
     *
     * @param contact the value for v_report_salesdata.contact
     *
     * @mbg.generated Thu Nov 10 11:26:04 CST 2016
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_report_salesdata.phone
     *
     * @return the value of v_report_salesdata.phone
     *
     * @mbg.generated Thu Nov 10 11:26:04 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_report_salesdata.phone
     *
     * @param phone the value for v_report_salesdata.phone
     *
     * @mbg.generated Thu Nov 10 11:26:04 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_report_salesdata.saleday
     *
     * @return the value of v_report_salesdata.saleday
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public Date getSaleday() {
        return saleday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_report_salesdata.saleday
     *
     * @param saleday the value for v_report_salesdata.saleday
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public void setSaleday(Date saleday) {
        this.saleday = saleday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_report_salesdata.saletotal
     *
     * @return the value of v_report_salesdata.saletotal
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public Double getSaletotal() {
        return saletotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_report_salesdata.saletotal
     *
     * @param saletotal the value for v_report_salesdata.saletotal
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public void setSaletotal(Double saletotal) {
        this.saletotal = saletotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_report_salesdata.qty
     *
     * @return the value of v_report_salesdata.qty
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_report_salesdata.qty
     *
     * @param qty the value for v_report_salesdata.qty
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_report_salesdata.imgfile
     *
     * @return the value of v_report_salesdata.imgfile
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public String getImgfile() {
        return imgfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_report_salesdata.imgfile
     *
     * @param imgfile the value for v_report_salesdata.imgfile
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public void setImgfile(String imgfile) {
        this.imgfile = imgfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_report_salesdata.reviewed
     *
     * @return the value of v_report_salesdata.reviewed
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public Integer getReviewed() {
        return reviewed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_report_salesdata.reviewed
     *
     * @param reviewed the value for v_report_salesdata.reviewed
     *
     * @mbg.generated Mon Nov 07 12:12:33 CST 2016
     */
    public void setReviewed(Integer reviewed) {
        this.reviewed = reviewed;
    }
}